数据预处理  
作用：1.平衡权重大小  2提升模型精度  
使用：连续特征   训练集和测试集都需特征缩放吗？都需要  

In [1]:
import numpy as np
from sklearn.preprocessing import StandardScaler, MinMaxScaler # 标准化， 归一化
import warnings
warnings.filterwarnings('ignore') # 忽略警告

In [2]:
# x1, x2, y
data = np.array([
    [2104, 3, 399900],
    [1600, 3, 329900],
    [2400, 3, 369000],
    [1416, 2, 232000],
    [3000, 4, 539900],
    [1985, 4, 299900]
])
# 提取特征
x = data[:, :-1]

In [3]:
# 创建模型  归一化
model = MinMaxScaler()
# 处理数据   查找模型最大值和最小值
model.fit(x) 
# 计算结果
x_ = model.transform(x)
x_ 

array([[0.43434343, 0.5       ],
       [0.11616162, 0.5       ],
       [0.62121212, 0.5       ],
       [0.        , 0.        ],
       [1.        , 1.        ],
       [0.35921717, 1.        ]])

In [4]:
# 归一化之前的结果
model.inverse_transform(x_)

array([[2.104e+03, 3.000e+00],
       [1.600e+03, 3.000e+00],
       [2.400e+03, 3.000e+00],
       [1.416e+03, 2.000e+00],
       [3.000e+03, 4.000e+00],
       [1.985e+03, 4.000e+00]])

In [5]:
# 标准化
model = StandardScaler()
model.fit(x)
model.transform(x)

array([[ 0.03805676, -0.24253563],
       [-0.92903261, -0.24253563],
       [ 0.60602988, -0.24253563],
       [-1.28209698, -1.69774938],
       [ 1.75732674,  1.21267813],
       [-0.19028379,  1.21267813]])

离散值预处理

In [6]:
import pandas as pd

In [7]:
# 数学模型不能出现字符
df = pd.read_csv('test.txt')
df.head()

季节  气温
0  春  25
1  夏  40
2  秋  15
3  冬  -3

In [8]:
# 将字符转为数字  标签化
from sklearn.preprocessing import LabelEncoder

In [9]:
x = df.iloc[:, :-1]
model = LabelEncoder()
# 转为数字
x_ = model.fit_transform(x)
x_

array([2, 1, 3, 0])

In [10]:
# 独热编码   将标签化的数值进行升维处理
from sklearn.preprocessing import OneHotEncoder

In [11]:
# 独热对象
onehot = OneHotEncoder()
x_onehot = onehot.fit_transform(x_.reshape(-1, 1)) 
# 使用独热方式处理+ toarray()
print(x_onehot.toarray())

[[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]]
