逻辑回归  
二分类    扩展多分类（OVO，ovr）
与线性回归原理类似（分类线 $ z=wx+b, sigmoid函数，用来计算样本正类别概率 \hat{y}=\dfrac{1}{1+e^{-z}} $）

In [1]:
# 调库
from sklearn.datasets import load_iris # 鸢尾花数据集   150条  4个特征  3个分类
from sklearn.linear_model import LogisticRegression # 逻辑回归 分类模型
from sklearn.model_selection import train_test_split, GridSearchCV # 数据切分， 模型调参
from sklearn.preprocessing import StandardScaler, OneHotEncoder # 数据预处理操作
import warnings
warnings.filterwarnings('ignore')

In [2]:
# 提取数据
x, y = load_iris(return_X_y=True)
print(x.shape)
print(y.shape)
print(x[:5])

(150, 4)
(150,)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [3]:
# 特征都是连续值，需要特征缩放
std = StandardScaler()
# 转化x进行标准化处理
x = std.fit_transform(x)
# y一维数据，需要转换为二维数据
y = y.reshape(-1, 1)
print(x[:5])
print(y.shape)

[[-0.90068117  1.01900435 -1.34022653 -1.3154443 ]
 [-1.14301691 -0.13197948 -1.34022653 -1.3154443 ]
 [-1.38535265  0.32841405 -1.39706395 -1.3154443 ]
 [-1.50652052  0.09821729 -1.2833891  -1.3154443 ]
 [-1.02184904  1.24920112 -1.34022653 -1.3154443 ]]
(150, 1)


In [4]:
# 切分数据集
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=123)

In [5]:
help(LogisticRegression)

Help on class LogisticRegression in module sklearn.linear_model.logistic:

class LogisticRegression(sklearn.base.BaseEstimator, sklearn.linear_model.base.LinearClassifierMixin, sklearn.linear_model.base.SparseCoefMixin)
 |  LogisticRegression(penalty='l2', dual=False, tol=0.0001, C=1.0, fit_intercept=True, intercept_scaling=1, class_weight=None, random_state=None, solver='warn', max_iter=100, multi_class='warn', verbose=0, warm_start=False, n_jobs=None)
 |  
 |  Logistic Regression (aka logit, MaxEnt) classifier.
 |  
 |  In the multiclass case, the training algorithm uses the one-vs-rest (OvR)
 |  scheme if the 'multi_class' option is set to 'ovr', and uses the cross-
 |  entropy loss if the 'multi_class' option is set to 'multinomial'.
 |  (Currently the 'multinomial' option is supported only by the 'lbfgs',
 |  'sag' and 'newton-cg' solvers.)
 |  
 |  This class implements regularized logistic regression using the
 |  'liblinear' library, 'newton-cg', 'sag' and 'lbfgs' solvers. It c

In [6]:
# 逻辑回归调参处理
lr = LogisticRegression() # 创建模型
pg = {'penalty': ['l1', 'l2'], 'C': [1,2,5,10]}# penalty 选择处理的正则化方式  C 正则化系数的倒数
model = GridSearchCV(lr, pg, cv=3)
model.fit(x_train, y_train)
print(model.best_score_)
print(model.best_params_)

0.95
{'C': 5, 'penalty': 'l1'}


In [12]:
# 选择最优参数创建模型
model = LogisticRegression(penalty='l1', C=5)
model.fit(x_train, y_train)
print('测试集得分：', model.score(x_test, y_test))
# 每一行代表的是一个样本对应三个类别预测的概率， 三个概率和为1，预测的类别是每一行中概率最大值
print('测试集的概率\n', model.predict_proba(x_test)[:5])
print('测试集预测结果\n', model.predict(x_test)[:5])

测试集得分： 0.9666666666666667
测试集的概率
 [[1.33342880e-04 6.43088550e-01 3.56778107e-01]
 [6.32536800e-05 2.24614518e-01 7.75322228e-01]
 [1.87890968e-05 2.73523462e-01 7.26457749e-01]
 [3.52324698e-02 9.61383341e-01 3.38418886e-03]
 [8.92845033e-01 1.07154967e-01 1.12809174e-13]]
测试集预测结果
 [1 2 2 1 0]
